[package]
name = "minijinja-cabi"
version = "2.4.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
minijinja = { version = "2.4.0", path = "../minijinja", features = ["loader", "custom_syntax"] }
